import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import NavBar from './NavBar'
import { Suspense } from 'react';
import AuthProvider from './auth/Provider';
import GoogleAnalyticsScript from './GoogleAnalyticsScript'
import { Inter, Roboto } from 'next/font/google';
import localFont from "next/font/local";



const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '500']
});

const poppins = localFont({
  src:'../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body className={poppins.variable}>
        <AuthProvider>
          <NavBar />
          <main className='p-5'>
            <Suspense fallback={<p>Loading...</p>}>
              {children}
            </Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
